Fix go.mod gomega
When we ran Ginkgo v2 tests for the first time we got the following
error:

```
  go install github.com/onsi/ginkgo/v2/ginkgo
  go install github.com/onsi/gomega/matchers
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
go: downloading github.com/onsi/ginkgo/v2 v2.15.0
go: downloading github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
go: downloading golang.org/x/tools v0.17.0
go: downloading github.com/google/pprof v0.0.0-20230912144702-c363fe2c2ed8
missing go.sum entry for module providing package github.com/onsi/gomega/matchers; to add:
	go mod download github.com/onsi/gomega
Error: Process completed with exit code 1.
```