Fix lint error
Despite fixing `golangci-lint` to v1.21.0, we have started to see a new
lint error in code that has not changed:
```
golangci-lint run
api/cloudcontroller/ccv3/metadata.go:99:12: Error return value of `client.newHTTPRequest` is not checked (errcheck)
		request, _ = client.newHTTPRequest(requestOptions{
		         ^
```

It does seem that an error is being ignored, so we have fixed that.

Co-authored-by: Marcela Campo <mcampo@pivotal.io>