🐞 V7 `auth`: update test expectations
We've obsoleted client credentials in the config file, and now our
`oauth` test expects the appropriate error message.

fixes <https://ci.cli.fun/teams/main/pipelines/V7/jobs/integration-linux-bosh-lite/builds/419>:
```
Got stuck at:
    Error: Support for manually writing your client credentials to config.json has been removed. For similar functionality please use `cf auth --client-credentials`.

Waiting for:
    Credentials were rejected, please try again.

/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/v7/isolated/oauth_client_test.go:76
```

[#172316246]

Co-authored-by: Belinda Liu <bliu@pivotal.io>
Co-authored-by: Brian Cunnie <bcunnie@pivotal.io>